"""Initial Schema

Revision ID: 6a60219f9f32
Revises: 
Create Date: 2025-12-08 20:40:07.123526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a60219f9f32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('catalog_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('distance_ly', sa.Float(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_bought', sa.Boolean(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stars_catalog_id'), 'stars', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_stars_common_name'), 'stars', ['common_name'], unique=False)
    op.create_index(op.f('ix_stars_id'), 'stars', ['id'], unique=False)
    op.create_index(op.f('ix_stars_scientific_name'), 'stars', ['scientific_name'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('includes_certificate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_stars_scientific_name'), table_name='stars')
    op.drop_index(op.f('ix_stars_id'), table_name='stars')
    op.drop_index(op.f('ix_stars_common_name'), table_name='stars')
    op.drop_index(op.f('ix_stars_catalog_id'), table_name='stars')
    op.drop_table('stars')
    # ### end Alembic commands ###
